import { z } from "zod";

export const SettingsValidator = z.object({
  outputPath: z.string().optional(),
  outputTemplate: z.string().optional(),
  turboMode: z.boolean().optional(),
  allowDiscordRPC: z.boolean().optional(),
  buildChannel: z.enum(["default", "stable", "nightly", "master"]).optional(),
  ffmpegLocation: z.string().optional(),
  allSubtitles: z.boolean().optional(),
  annotations: z.boolean().optional(),
  autoGenerateSubtitles: z.boolean().optional(),
  description: z.boolean().optional(),
  disablePartFiles: z.boolean().optional(),
  metadata: z.boolean().optional(),
  noMtime: z.boolean().optional(),
  notifications: z.boolean().optional(),
  promptForPlaylist: z.boolean().optional(),
  removeOnFinish: z.boolean().optional(),
  restrictFileNames: z.boolean().optional(),
  subtitles: z.boolean().optional(),
  thumbnail: z.boolean().optional(),
  customUserAgent: z.boolean().optional(),
  forceIPVersion: z.enum(["no-force", "ipv4", "ipv6"]).optional(),
  preferInsecure: z.boolean().optional(),
  proxyIpAddress: z.string().optional(),
  rateLimit: z.string().optional(),
  refererUrl: z.string().optional(),
  socketTimeout: z.string().optional(),
  sourceIPAddress: z.string().optional(),
  suppressHTTPCertificateValidation: z.boolean().optional(),
  throttleRate: z.string().optional(),
  unit: z.enum(["gigabyte", "megabyte", "kilobyte", "byte"]).optional(),
  audioQuality: z.number().optional(),
  covertArt: z.boolean().optional(),
  customPostRenderingCommand: z.string().optional(),
  embedChapters: z.boolean().optional(),
  sponsorblock: z.boolean().optional(),
  keepVideo: z.boolean().optional(),
  splitChapters: z.boolean().optional(),
  sponsorblockAPIUrl: z.string().optional(),
  sponsorblockRemove: z.string().optional(),
});

export type ISettings = z.infer<typeof SettingsValidator>;
